#!/usr/bin/env python3
"""Plot travel-time histograms grouped by transfer counts from path search results.

功能：
    - 读取 `find_paths_dfs.py` 输出的路径 JSON，按照 `transfer_count` 将行程总时长分组；
    - 绘制直达、一次换乘、两次换乘（及其他）的时长分布。

使用方法：
    python visualizations/plot_transfer_histogram.py Result_Finding/path_A_B.json \
        --bins 30 --output visualizations/plot.png
    省略 --output 时会直接弹出图形窗口。
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt


def load_transfer_times(results_path: Path) -> Dict[int, List[int]]:
    grouped: Dict[int, List[int]] = {0: [], 1: [], 2: [], -1: []}
    with results_path.open('r', encoding='utf-8') as fp:
        data = json.load(fp)

    if isinstance(data, dict) and 'train' in data:
        raise ValueError('Expected path result list, got schedule-style JSON.')

    for entry in data:
        minutes = entry.get('total_minutes')
        transfers = entry.get('transfer_count')
        if minutes is None or transfers is None:
            continue
        if transfers in grouped:
            grouped[transfers].append(minutes)
        else:
            grouped[-1].append(minutes)
    return grouped


def plot_hist(grouped: Dict[int, List[int]], bins: int, output: Path | None, source_label: str) -> None:
    try:
        import matplotlib.pyplot as plt  # type: ignore
        plt.rcParams['font.family'] = 'Microsoft YaHei'  # 替换为你选择的字体
    except Exception:
        print("[图表] matplotlib 不可用，跳过可视化生成。可使用 'pip install matplotlib' 安装后重试。")
        return
    
    labels = {
        0: 'Direct (0 transfers)',
        1: '1 transfer',
        2: '2 transfers',
        -1: 'Other'
    }
    colors = {0: '#2E86AB', 1: '#F6C85F', 2: '#6F4E7C', -1: '#9E9E9E'}
    plt.figure(figsize=(10, 6))
    plotted = False
    for key in (0, 1, 2, -1):
        times = grouped.get(key, [])
        if not times:
            continue
        plotted = True
        plt.hist(times, bins=bins, alpha=0.6, label=f"{labels[key]} (n={len(times)})", color=colors[key])

    if not plotted:
        raise ValueError('No valid entries with total_minutes found in input file.')

    plt.title(f'Travel Time Distribution by Transfer Count\nInput: {source_label}')
    plt.xlabel('Total minutes')
    plt.ylabel('Frequency')
    plt.legend()
    plt.tight_layout()

    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output, dpi=150)
        print(f"Saved histogram to {output}")
    else:
        plt.show()


def main() -> None:
    parser = argparse.ArgumentParser(description='Plot travel-time histograms by transfer count.')
    parser.add_argument('input', help='Path to JSON results generated by find_paths_dfs')
    parser.add_argument('--bins', type=int, default=20, help='Number of histogram bins (default: 20)')
    parser.add_argument('--output', help='Optional path to save the figure instead of displaying it')
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f'Input file not found: {input_path}')

    output_path = Path(args.output) if args.output else None

    grouped = load_transfer_times(input_path)
    plot_hist(grouped, bins=args.bins, output=output_path, source_label=input_path.name)


if __name__ == '__main__':
    # CLI 入口：传入路径搜索生成的 JSON，可选 --bins / --output 参数控制直方图
    main()
